version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - streamgate-net

  control-plane:
    build:
      context: .
      dockerfile: build/package/Dockerfile.control_plane
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    volumes:
      - ./control_plane:/app/control_plane  # Hot reload logic for dev
    networks:
      - streamgate-net

  data-plane:
    build:
      context: .
      dockerfile: build/package/Dockerfile.data_plane
    ports:
      - "8081:8081"      # TCP Log Ingest
      - "8082:8082/udp"  # UDP Log Ingest
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
      - control-plane
    networks:
      - streamgate-net

networks:
  streamgate-net:
    driver: bridge
